@startuml
title opponent robot state machine

' states
state Follow 
state Park 
state Fight
state Stop 

' relationships
[*] -d-> Stop

Stop -l-> Park : gesture=point_left or point_right
Stop -r-> Fight : gesture=two_fists
Stop -d-> Follow : gesture=open_hand

Follow --> Park : gesture=point_left or point_right
Follow --> Fight : gesture=two_fists
Follow --> Stop : gesture=palm_down

Park --> Follow : gesture=open_hand
Park --> Fight : gesture=two_fists
Park --> Stop : gesture=palm_down

Fight --> Park : gesture=point_left or point_right
Fight --> Follow : gesture=open_hand
Fight --> Stop : gesture=palm_down

@enduml